### PR TITLE
Materialize FileInfo from DirEntry in WalkDiskDir for Go 1.26

### LINKED ISSUE #4796: fs.DirEntry does not implement fs.FileInfo error in `go-1.26`
**What happened**:

```bash
17:42:10  ../../go/pkg/mod/github.com/anchore/syft@v1.42.4/internal/file/squashfs.go:29:30: cannot use info (variable of interface type fs.DirEntry) as os.FileInfo value in argument to walkDiskDir: fs.DirEntry does not implement fs.FileInfo (missing method ModTime)
17:42:10  ../../go/pkg/mod/github.com/anchore/syft@v1.42.4/internal/file/squashfs.go:78:38: cannot use d1 (variable of interface type fs.DirEntry) as os.FileInfo value in argument to walkDiskDir: fs.DirEntry does not implement fs.FileInfo (missing method ModTime)
```

**What you expected to happen**:

TBD

**Steps to reproduce the issue**:

The following worked in `go-1.25.x?` and started to give the above error in `go-1.26.2`

`return ac, filepath.Walk(gitRoot, func(path string, info os.FileInfo, err error) error {`

**Anything else we need to know?**:

I see that your main branch have bumped to `1.26.2`, so this might be fixed in the next release.

**Environment**:
- Output of `syft version`: `v1.42.4`
- OS (e.g: `cat /etc/os-release` or similar):

### PR DESCRIPTION
**Pull request by joaquinhuigomez**
Go 1.26 removed `ModTime` from `fs.DirEntry`, so `fs.DirEntry` no longer satisfies `os.FileInfo`. `WalkDiskDir` passed `DirEntry` values from `fsys.ReadDir` directly into `walkDiskDir(… d os.FileInfo, …)`, which now fails to build against the go1.26 toolchain.

Convert each entry via a small helper that prefers a direct `FileInfo` type assertion and falls back to `DirEntry.Info()` otherwise. Behavior is unchanged for callers that already return `FileInfo` values.

Fixes #4796

### CODE REVIEW

**Comment by sastorsl** [comment]
@joaquinhuigomez I see that the DCO test fails.
Perhaps you can fix your commit with `git commit --amend --no-edit --signoff` and force push the updated commit?
