### ISSUE TITLE
fs.DirEntry does not implement fs.FileInfo error in `go-1.26`

### ISSUE THREAD

**Issue by sastorsl** [anchore/syft#4796]
**What happened**:

```bash
17:42:10  ../../go/pkg/mod/github.com/anchore/syft@v1.42.4/internal/file/squashfs.go:29:30: cannot use info (variable of interface type fs.DirEntry) as os.FileInfo value in argument to walkDiskDir: fs.DirEntry does not implement fs.FileInfo (missing method ModTime)
17:42:10  ../../go/pkg/mod/github.com/anchore/syft@v1.42.4/internal/file/squashfs.go:78:38: cannot use d1 (variable of interface type fs.DirEntry) as os.FileInfo value in argument to walkDiskDir: fs.DirEntry does not implement fs.FileInfo (missing method ModTime)
```

**What you expected to happen**:

TBD

**Steps to reproduce the issue**:

The following worked in `go-1.25.x?` and started to give the above error in `go-1.26.2`

`return ac, filepath.Walk(gitRoot, func(path string, info os.FileInfo, err error) error {`

**Anything else we need to know?**:

I see that your main branch have bumped to `1.26.2`, so this might be fixed in the next release.

**Environment**:
- Output of `syft version`: `v1.42.4`
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by sastorsl** [comment]
Any hope of getting the mentioned PR into a release?
We now have a couple of projects blocked by this - so would be very grateful to see a fix.
